version: "3.3"
services:
  readonly:
    image: nuttzipper/rnode:dev
    user: root
    networks:
      - rchain-net
    container_name: rnode.readonly
    ports:
      - "30401:40401"
      - "30405:40405"
    command:
      [
        "run",
        "--bootstrap=rnode://22457f2b426a31b5b497376ed4341a2092d5c6cc@$BOOTSTRAP_HOST?protocol=40400&discovery=40404",
        "--host=$READONLY_HOST",
        "--allow-private-addresses",
        "--synchrony-constraint-threshold=$SYNCHRONY_CONSTRAINT_THRESHOLD",
      ]
    volumes:
      - ./data/observer:/var/lib/rnode/
      - ./conf/observer.conf:/var/lib/rnode/rnode.conf
      - ./conf/logback.xml:/var/lib/rnode/logback.xml

networks:
  rchain-net:
