version: "3.3"

services:
  propose:
    build: ./proposerImage
    command: ["--config", "/proposer_config.yml"]
    volumes:
      - ./resources/nil.rho:/nil.rho
      - ./resources/proposer_config.yml:/proposer_config.yml
      - ./resources/error.txt:/error.txt
      - ./resources/error.log:/error.log
    networks:
      - rchain-net
networks:
  rchain-net:
